.PHONY: all setup run clean update test

all: setup

setup:
	@echo "Setting up the project..."
	@chmod +x scripts/setup.sh
	@./scripts/setup.sh

run:
	@echo "Running the main script..."
	@source venv/bin/activate && python src/main.py

clean:
	@echo "Cleaning up..."
	@rm -rf venv rpi-rgb-led-matrix
	@find . -type f -name '*.pyc' -delete
	@find . -type d -name '__pycache__' -delete

update:
	@echo "Updating the project..."
	@git pull
	@source venv/bin/activate && pip install -r requirements.txt

test:
	@echo "Running tests..."
	@source venv/bin/activate && python -m unittest discover tests

lint:
	@echo "Linting the code..."
	@source venv/bin/activate && pylint src/*.py